refactor, ci: switch clang-format to LLVM 15
Bump required clang-format version to 15 and fix the following noise:

./macosx/VDKQueue/VDKQueue.h:101:42: error: code should be clang-formatted [-Wclang-format-violations]
typedef NS_OPTIONS(u_int, VDKQueueNotify)
                                         ^
./libtransmission/variant.cc:58:17: error: code should be clang-formatted [-Wclang-format-violations]
        delete[]((char*)(str->str.str));
                ^

Signed-off-by: Mike Gelfand <mikedld@mikedld.com>
Signed-off-by: Dmitry Antipov <dantipov@cloudlinux.com>