Seperate functions since method can't return a structure?
Should solve error: `error C2526: 'tr_getDirFreeSpace': C linkage function cannot return C++ class 'tr_disk_space'`
https://trtc.mikedld.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=106738&_focus=2612