ci: do not install homebrew libnatpmp on macos 11
Temporary workaround for what appears to be an upstream issue
from https://github.com/Homebrew/homebrew-core/pull/129122 --
that landed at the same time that this breakage was introduced.

I haven't opened an upstream issue yet since I haven't tested
firsthand on a macOS box.

The breakage is:

In file included from /Users/runner/work/transmission/transmission/src/libtransmission/port-forwarding-natpmp.cc:16:
/usr/local/include/natpmp.h:52:10: fatal error: 'natpmp_declspec.h' file not found
         ^~~~~~~~~~~~~~~~~~~
1 error generated.