build: Use CXX symbol checking for libutp
Configuring yielded:

      Could NOT find UTP (missing: UTP_LIBRARY UTP_INCLUDE_DIR)
    Call Stack (most recent call first):
      /very/long/path/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
      cmake/FindUTP.cmake:74 (find_package_handle_standard_args)
      cmake/TrMacros.cmake:136 (find_package)
      CMakeLists.txt:503 (tr_add_external_auto_library)

    -- Configuring incomplete, errors occurred!
    See also "/home/user/dev/torrents/transmission/build/CMakeFiles/CMakeOutput.log".
    See also "/home/user/dev/torrents/transmission/build/CMakeFiles/CMakeError.log".

The error logs included this bit:

    /very/long/path/bin/ld: /very/long/path/lib/libutp.a(utp_internal.cpp.o): in function `UTP_FreeAll(UTPSocketHT*)':
    (.text+0xc15): undefined reference to `operator delete(void*)'

After changing the check method to use `check_cxx_symbol_exists` instead,
configuring yielded:

    -- Found UTP: /very/long/path/lib/libutp.a