fix: FTBFS with glibmm-2.68 (#8552)
13:45:53 /home/fedora/jenkins/workspace/trunk-linux/transmission-4.1.0-beta.5+r6c92d06854/gtk/DetailsDialog.cc:974:52:   required from here
13:45:53   974 |         bool const is_uniform = std::ranges::all_of(stats, [&baseline](auto const& st) { return baseline == st.error_string; });
13:45:53       |                                 ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
13:45:53 /usr/include/glibmm-2.68/glibmm/ustring.h:1501:22: error: no matching function for call to ‘Glib::ustring::compare(const std::__cxx11::basic_string<char>&) const’
13:45:53  1501 |   return (lhs.compare(rhs) == 0);
13:45:53       |           ~~~~~~~~~~~^~~~~